steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rachits-project/chatgpt-app', '.']
    id: 'Build Docker Image'
    env:
      - 'DOCKER_BUILDKIT=1'
    allowFailure: false
    dir: './'
    timeout: '1200s'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rachits-project/chatgpt-app']
    id: 'Push Docker Image'
    waitFor: ['Build Docker Image']
    allowFailure: false
    timeout: '600s'

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'chatgpt-app', '--image', 'gcr.io/rachits-project/chatgpt-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
    id: 'Deploy to Cloud Run'
    waitFor: ['Push Docker Image']
    allowFailure: false
    timeout: '600s'

timeout: '2400s'
queueTtl: '600s'
logsBucket: 'gs://rachits-project-cloudbuild-logs'
options:
  env:
    - 'CLOUDSDK_CORE_DISABLE_PROMPTS=1'
  logging: GCS_ONLY  # Use this to log to the specified bucket
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: '20'
  logStreamingOption: 'STREAM_ON'
substitutions:
  _REGION: 'us-central1'
tags:
  - 'chatgpt-app'
  - 'cloud-run'
serviceAccount: 'cloud-build-sa@rachits-project.iam.gserviceaccount.com'
images:
  - 'gcr.io/rachits-project/chatgpt-app'
